# Generated by Django 4.0 on 2022-01-05 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False)),
                ('blog_content', models.JSONField(blank=True, db_column='BLOG_CONTENT', null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_column='CREATED_DATE')),
                ('modified_date', models.DateTimeField(auto_now_add=True, db_column='MODIFIED_DATE')),
                ('author', models.CharField(db_column='AUTHOR', max_length=30)),
            ],
            options={
                'db_table': 'BLOG',
            },
        ),
    ]
