# Generated by Django 4.0 on 2022-01-05 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='author',
            field=models.TextField(db_column='AUTHOR', max_length=30),
        ),
    ]
