# Generated by Django 4.0 on 2022-01-05 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blogs_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='author',
            field=models.CharField(db_column='AUTHOR', max_length=30),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='blog_content',
            field=models.TextField(blank=True, db_column='BLOG_CONTENT', null=True),
        ),
    ]
