# Generated by Django 4.0 on 2022-01-06 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blogs_author_alter_blogs_blog_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='blog_title',
            field=models.TextField(db_column='BLOG_TITLE', default='this is title', max_length=30),
            preserve_default=False,
        ),
    ]
