# Generated by Django 4.0 on 2022-01-06 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blogs_blog_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='category',
            field=models.CharField(db_column='CATEGORY', default='Tech', max_length=30),
            preserve_default=False,
        ),
    ]
