# Generated by Django 4.0 on 2022-02-11 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_column='CREATED_DATE')),
                ('modified_date', models.DateTimeField(auto_now_add=True, db_column='MODIFIED_DATE')),
                ('full_name', models.CharField(db_column='FULL_NAME', max_length=70)),
                ('contact_email', models.EmailField(db_column='CONTACT_EMAIL', max_length=254)),
                ('contact_message', models.TextField(db_column='CONTACT_MESSAGE')),
            ],
            options={
                'db_table': 'CONTACT_US',
            },
        ),
    ]
